In [77]:
import pandas as pd

stations_df = pd.read_csv("stations.csv")
readings_df = pd.read_csv("activity_readings.csv")

In [73]:
len(readings_df[invalid_mask])

9

In [7]:
print("Stations:", stations_df["station_id"].nunique())
print("Readings:", len(readings_df))
print()
print(readings_df.isna().sum())
print(readings_df["source_id"].value_counts())

Stations: 8
Readings: 2092

event_id     2
source_id    2
timestamp    1
value        2
dtype: int64
source_id
station-north-01    262
station-west-01     262
station-east-01     261
station-east-02     261
station-north-02    261
station-south-01    261
station-south-02    261
station-west-02     261
Name: count, dtype: int64

In [27]:
stations_unique = set(stations_df["station_id"].dropna())
readings_unique = set(readings_df["source_id"].dropna())


print(stations_unique)
print(readings_unique)
are_equal = stations_unique == readings_unique
print(f"equal = {are_equal}")

{'station-west-01', 'station-east-02', 'station-east-01', 'station-south-01', 'station-west-02', 'station-south-02', 'station-north-01', 'station-north-02'}
{'station-west-01', 'station-east-02', 'station-east-01', 'station-south-01', 'station-south-02', 'station-west-02', 'station-north-01', 'station-north-02'}
equal = True

In [31]:
result = readings_df.groupby("source_id")["value"].agg(['min','max'])

print(result)

                    min   max
source_id
station-east-01    19.4   abc
station-east-02     0.0  99.5
station-north-01     --  61.0
station-north-02   37.8  97.0
station-south-01  100.0  99.9
station-south-02  104.6  87.3
station-west-01   103.2  93.4
station-west-02   100.3  99.6

In [33]:
converted = pd.to_numeric(readings_df["value"], errors='coerce')

invalid_mask = converted.isna() & readings_df["value"].notna()

invalid_values = readings_df.loc[invalid_mask, "value"].unique()

In [34]:
print(invalid_values)

<StringArray>
['abc', '--', '12,5']
Length: 3, dtype: str

In [39]:
print(stations_df.duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [41]:
converted.agg(
    ["count", "mean", "min", "max", "std"]
)

count    2087.000000
mean       70.469142
min         0.000000
max       172.900000
std        30.964745
Name: value, dtype: float64

In [44]:
readings_df[
    readings_df["source_id"].isna()
    & readings_df["parsed_value"].notna()
]

,event_id,source_id,timestamp,value,parsed_timestamp,parsed_value
554,e00555,NaN,2026-09-09T09:09:00Z,58.0,2026-09-09 09:09:00+00:00,58.0
691,e00692,NaN,2026-09-09T09:26:00Z,101.4,2026-09-09 09:26:00+00:00,101.4

In [54]:
readings_df["value"].isna().sum()

np.int64(2)

In [74]:
date_converted = pd.to_datetime(readings_df["timestamp"], errors='coerce')
date_mask = date_converted.isna()

numeric_converted = pd.to_numeric(readings_df["value"], errors='coerce')
value_mask = numeric_converted.isna()

invalid_mask = (readings_df["event_id"].isna()) | (readings_df["source_id"].isna()) | date_mask | value_mask

print(readings_df[invalid_mask].shape[0])

12

In [78]:
readings_df.head()

  event_id         source_id             timestamp value
0   e00001   station-east-01  2026-09-09T08:00:00Z  26.6
1   e00002   station-east-02  2026-09-09T08:00:00Z  42.1
2   e00003  station-north-01  2026-09-09T08:00:00Z  44.5
3   e00004  station-north-02  2026-09-09T08:00:00Z  62.5
4   e00005  station-south-01  2026-09-09T08:00:00Z  93.4

In [80]:
readings_df.describe()

       event_id         source_id             timestamp value
count      2090              2090                  2091  2090
unique     2090                 8                   262   881
top      e00001  station-north-01  2026-09-09T08:35:00Z  25.0
freq          1               262                     9    28